"""Initial migration with all tables

Revision ID: 65caac59bfd3
Revises: 
Create Date: 2025-09-13 03:16:48.111171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65caac59bfd3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('name', sa.String(length=100), nullable=False, comment='장비 이름'),
    sa.Column('device_type', sa.Enum('MULTIMETER', 'OSCILLOSCOPE', 'POWER_SUPPLY', 'FUNCTION_GENERATOR', 'OTHER', name='devicetype'), nullable=False, comment='장비 타입'),
    sa.Column('manufacturer', sa.String(length=100), nullable=True, comment='제조사'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='모델명'),
    sa.Column('firmware_version', sa.String(length=50), nullable=True, comment='펌웨어 버전'),
    sa.Column('port', sa.String(length=20), nullable=False, comment='통신 포트 (예: COM1)'),
    sa.Column('baud_rate', sa.Integer(), nullable=True, comment='보드레이트'),
    sa.Column('data_bits', sa.Integer(), nullable=True, comment='데이터 비트'),
    sa.Column('parity', sa.String(length=10), nullable=True, comment='패리티'),
    sa.Column('stop_bits', sa.Integer(), nullable=True, comment='스톱 비트'),
    sa.Column('flow_control', sa.String(length=20), nullable=True, comment='흐름 제어'),
    sa.Column('timeout', sa.Integer(), nullable=True, comment='타임아웃 (초)'),
    sa.Column('idn_command', sa.String(length=50), nullable=True, comment='장비 식별 명령어'),
    sa.Column('scpi_commands', sa.JSON(), nullable=True, comment='장비별 SCPI 명령어 목록'),
    sa.Column('connection_status', sa.Enum('CONNECTED', 'DISCONNECTED', 'ERROR', name='connectionstatus'), nullable=True, comment='연결 상태'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='사용 여부'),
    sa.Column('response_delay', sa.Float(), nullable=True, comment='명령어 응답 지연 시간 (초)'),
    sa.Column('max_retry_count', sa.Integer(), nullable=True, comment='최대 재시도 횟수'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('inspection_models',
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='모델 이름'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='모델 설명'),
    sa.Column('p1_lower_limit', sa.Float(), nullable=False, comment='P1 하한값'),
    sa.Column('p1_upper_limit', sa.Float(), nullable=False, comment='P1 상한값'),
    sa.Column('p2_lower_limit', sa.Float(), nullable=False, comment='P2 하한값'),
    sa.Column('p2_upper_limit', sa.Float(), nullable=False, comment='P2 상한값'),
    sa.Column('p3_lower_limit', sa.Float(), nullable=False, comment='P3 하한값'),
    sa.Column('p3_upper_limit', sa.Float(), nullable=False, comment='P3 상한값'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='모델 사용 여부'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name')
    )
    op.create_index(op.f('ix_inspection_models_id'), 'inspection_models', ['id'], unique=False)
    op.create_table('system_logs',
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), nullable=False, comment='로그 레벨'),
    sa.Column('category', sa.Enum('SYSTEM', 'DEVICE', 'MEASUREMENT', 'API', 'WEBSOCKET', 'DATABASE', name='logcategory'), nullable=False, comment='로그 카테고리'),
    sa.Column('message', sa.String(length=500), nullable=False, comment='로그 메시지'),
    sa.Column('details', sa.Text(), nullable=True, comment='상세 정보'),
    sa.Column('module', sa.String(length=100), nullable=True, comment='모듈명'),
    sa.Column('function', sa.String(length=100), nullable=True, comment='함수명'),
    sa.Column('line_number', sa.Integer(), nullable=True, comment='라인 번호'),
    sa.Column('user_id', sa.String(length=100), nullable=True, comment='사용자 ID'),
    sa.Column('session_id', sa.String(length=50), nullable=True, comment='세션 ID'),
    sa.Column('device_id', sa.Integer(), nullable=True, comment='관련 장비 ID'),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='추가 데이터'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_table('test_settings',
    sa.Column('p1_measure_duration', sa.Float(), nullable=True, comment='P1 측정 시간'),
    sa.Column('wait_duration_1_to_2', sa.Float(), nullable=True, comment='P1-P2 대기 시간'),
    sa.Column('p2_measure_duration', sa.Float(), nullable=True, comment='P2 측정 시간'),
    sa.Column('wait_duration_2_to_3', sa.Float(), nullable=True, comment='P2-P3 대기 시간'),
    sa.Column('p3_measure_duration', sa.Float(), nullable=True, comment='P3 측정 시간'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='활성 설정 여부'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='설정 이름'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='설정 설명'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_settings_id'), 'test_settings', ['id'], unique=False)
    op.create_table('measurements',
    sa.Column('barcode', sa.String(length=100), nullable=False, comment='바코드'),
    sa.Column('session_id', sa.String(length=50), nullable=False, comment='검사 세션 ID'),
    sa.Column('inspection_model_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('P1', 'P2', 'P3', name='measurementphase'), nullable=False, comment='측정 단계 (P1/P2/P3)'),
    sa.Column('raw_data', sa.JSON(), nullable=True, comment='실시간 수집된 원시 데이터 배열'),
    sa.Column('min_value', sa.Float(), nullable=True, comment='최솟값'),
    sa.Column('max_value', sa.Float(), nullable=True, comment='최댓값'),
    sa.Column('avg_value', sa.Float(), nullable=True, comment='평균값'),
    sa.Column('std_deviation', sa.Float(), nullable=True, comment='표준편차'),
    sa.Column('result', sa.Enum('PASS', 'FAIL', 'ERROR', name='measurementresult'), nullable=False, comment='측정 결과'),
    sa.Column('lower_limit', sa.Float(), nullable=True, comment='적용된 하한값'),
    sa.Column('upper_limit', sa.Float(), nullable=True, comment='적용된 상한값'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='측정 시작 시간'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='측정 종료 시간'),
    sa.Column('duration', sa.Float(), nullable=True, comment='측정 시간 (초)'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['inspection_model_id'], ['inspection_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_id'), 'measurements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_id'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_test_settings_id'), table_name='test_settings')
    op.drop_table('test_settings')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_inspection_models_id'), table_name='inspection_models')
    op.drop_table('inspection_models')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
