"""Add barcode_scanner_settings table

Revision ID: 6f0b66e7e62b
Revises: 65caac59bfd3
Create Date: 2025-09-14 05:59:10.458240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f0b66e7e62b'
down_revision: Union[str, None] = '65caac59bfd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barcode_scanner_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port', sa.String(length=50), nullable=False, comment='시리얼 포트 (예: COM1, COM2)'),
    sa.Column('baudrate', sa.Integer(), nullable=False, comment='보드레이트'),
    sa.Column('data_bits', sa.Integer(), nullable=False, comment='데이터 비트'),
    sa.Column('stop_bits', sa.Integer(), nullable=False, comment='스톱 비트'),
    sa.Column('parity', sa.String(length=1), nullable=False, comment='패리티 (N/E/O)'),
    sa.Column('timeout', sa.Integer(), nullable=False, comment='타임아웃 (초)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('description', sa.Text(), nullable=True, comment='설명'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='수정일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barcode_scanner_settings_id'), 'barcode_scanner_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_barcode_scanner_settings_id'), table_name='barcode_scanner_settings')
    op.drop_table('barcode_scanner_settings')
    # ### end Alembic commands ###
